
\c customer_db

CREATE TABLE public.client (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    document_id character varying(20) NOT NULL,
    email character varying(100) NOT NULL,
    name character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone
);



ALTER TABLE public.client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Insertar client , testing data
INSERT INTO public.client (id, name, document_id, email, status, created_at, updated_at) VALUES
(1, 'Juan Pérez', '12345678', 'juan.perez@email.com', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'María García', '87654321', 'maria.garcia@email.com', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Carlos Rodríguez', '11223344', 'carlos.rodriguez@email.com', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Ana Martínez', '44332211', 'ana.martinez@email.com', 'INACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Luis Hernández', '55667788', 'luis.hernandez@email.com', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Laura Sánchez', '88776655', 'laura.sanchez@email.com', 'BLOCKED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Pedro Gómez', '99887766', 'pedro.gomez@email.com', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'Sofia López', '66778899', 'sofia.lopez@email.com', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Reiniciar la secuencia del ID
ALTER SEQUENCE client_id_seq RESTART WITH 9;
