
\c account_db

CREATE TABLE public.account (
	balance numeric(19, 2) NOT NULL,
	client_id int8 NOT NULL,
	created_at timestamp(6) NOT NULL,
	updated_at timestamp(6) NULL,
	"version" int8 NULL,
	account_number varchar(20) NOT NULL,
	account_type varchar(20) NOT NULL,
	status varchar(20) NOT NULL
);


CREATE TABLE public.audit_log (
	amount numeric(19, 2) NULL,
	new_balance numeric(19, 2) NULL,
	previous_balance numeric(19, 2) NULL,
	created_at timestamp(6) NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	account_number varchar(20) NOT NULL,
	status varchar(20) NULL,
	operation_type varchar(50) NOT NULL,
	transaction_id varchar(50) NULL,
	correlation_id varchar(100) NULL,
	description varchar(500) NULL
);



INSERT INTO public.account (account_number, client_id, balance, account_type, status, created_at, version) VALUES ('ACC001', 1, 5000.00, 'CHECKING', 'ACTIVE', CURRENT_TIMESTAMP, 0);
INSERT INTO public.account (account_number, client_id, balance, account_type, status, created_at, version) VALUES ('ACC002', 1, 10000.00, 'SAVINGS', 'ACTIVE', CURRENT_TIMESTAMP, 0);
INSERT INTO public.account (account_number, client_id, balance, account_type, status, created_at, version) VALUES ('ACC003', 2, 7500.00, 'CHECKING', 'ACTIVE', CURRENT_TIMESTAMP, 0);
INSERT INTO public.account (account_number, client_id, balance, account_type, status, created_at, version) VALUES ('ACC004', 2, 25000.00, 'BUSINESS', 'ACTIVE', CURRENT_TIMESTAMP, 0);
INSERT INTO public.account (account_number, client_id, balance, account_type, status, created_at, version) VALUES ('ACC005', 3, 1500.00, 'CHECKING', 'ACTIVE', CURRENT_TIMESTAMP, 0);
INSERT INTO public.account (account_number, client_id, balance, account_type, status, created_at, version) VALUES ('ACC006', 3, 50000.00, 'SAVINGS', 'ACTIVE', CURRENT_TIMESTAMP, 0);

-- Insert audit logs
INSERT INTO public.audit_log (account_number, transaction_id, operation_type, amount, previous_balance, new_balance, status, description, created_at) VALUES ('ACC001', NULL, 'ACCOUNT_CREATED', 5000.00, 0.00, 5000.00, 'SUCCESS', 'Initial account creation', CURRENT_TIMESTAMP);
INSERT INTO public.audit_log (account_number, transaction_id, operation_type, amount, previous_balance, new_balance, status, description, created_at) VALUES ('ACC002', NULL, 'ACCOUNT_CREATED', 10000.00, 0.00, 10000.00, 'SUCCESS', 'Initial account creation', CURRENT_TIMESTAMP);
INSERT INTO public.audit_log (account_number, transaction_id, operation_type, amount, previous_balance, new_balance, status, description, created_at) VALUES ('ACC003', NULL, 'ACCOUNT_CREATED', 7500.00, 0.00, 7500.00, 'SUCCESS', 'Initial account creation', CURRENT_TIMESTAMP);
INSERT INTO public.audit_log (account_number, transaction_id, operation_type, amount, previous_balance, new_balance, status, description, created_at) VALUES ('ACC004', NULL, 'ACCOUNT_CREATED', 25000.00, 0.00, 25000.00, 'SUCCESS', 'Initial account creation', CURRENT_TIMESTAMP);
INSERT INTO public.audit_log (account_number, transaction_id, operation_type, amount, previous_balance, new_balance, status, description, created_at) VALUES ('ACC005', NULL, 'ACCOUNT_CREATED', 1500.00, 0.00, 1500.00, 'SUCCESS', 'Initial account creation', CURRENT_TIMESTAMP);
INSERT INTO public.audit_log (account_number, transaction_id, operation_type, amount, previous_balance, new_balance, status, description, created_at) VALUES ('ACC006', NULL, 'ACCOUNT_CREATED', 50000.00, 0.00, 50000.00, 'SUCCESS', 'Initial account creation', CURRENT_TIMESTAMP);
