

CREATE TABLE public.client (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    document_id character varying(20) NOT NULL,
    email character varying(100) NOT NULL,
    name character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone
);



ALTER TABLE public.client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

